version: "2"
services:
  db:
    image: "mysql"
    volumes:
      - "./persist/database:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=aids"
    ports:
      - "3606:3306"
  api:
    image: "node"
    volumes:
      - ".:/usr/src"
      - "./persist/firmwares:/usr/firmwares"
    working_dir: "/usr/src"
    command: "npm run watch:poll"
    environment:
      - "DB_HOST=db"
      - "DB_USER=root"
      - "DB_PASSWORD=aids"
      - "FIRMWARE_DIR=/usr/firmwares"
    ports:
      - "80:80"
    links:
      - "db"